### ISSUE TITLE
Missing `multifile/1` directives

### ISSUE THREAD

**Issue by pmoura** [hhu-stups/prob-issues#175]
Non-exhaustive listing:

```text
*     Missing predicate directive: :-multifile user:portray_message/2.
*       while compiling object prob_cli
*       in file /Users/pmoura/ProB_src/src/prob_cli.pl at or above line 21
*     
*     Missing predicate directive: :-multifile user:runtime_entry/1.
*       while compiling object prob_cli
*       in file /Users/pmoura/ProB_src/src/prob_cli.pl at or above line 5161
```

**Comment by pmoura** [comment]
Also in the `find_whens.pl` file (around line 12).

**Comment by pmoura** [comment]
In `disprover_test_runner.pl`, inside the module:

```logtalk
portray_message(informational, _).
```

This is most likely a bug. It should be, I think:

```logtalk
:- multifile user:portray_message/2.
user:portray_message(informational, _).
```

Same in `kernel_objects.pl`(although the definition is currently commented out there).

**Comment by dgelessus** [comment]
Fixed all the `portray_message` definitions to have the `user:` prefix and a `multifile` declaration. This also matches what the SICStus docs for [`portray_message/2`](https://sicstus.sics.se/sicstus/docs/latest4/html/sicstus.html/mpg_002dref_002dportray_005fmessage.html) say.

I'm not sure about `user:runtime_entry/1` though. Since it defines an entry point, there should only ever be one `user:runtime_entry` definition from one file loaded at any time, so `multifile` seems incorrect. My guess is that when telling Logtalk to load all files in the src directory, it loads multiple files that are meant as standalone entry points, not modules that should be loaded at the same time. I recently moved most of these alternate entry points from *src* into a separate *tests* directory - that will probably eliminate the warnings about `user:runtime_entry` (and probably also some multiple definition errors, e. g. for `test_repl/0`).

**Comment by pmoura** [comment]
Indeed trying to load all files in the `src` directory is just a crude first attempt to run the linter and provide feedback. Logtalk applications use a much more strict approach where one of more [loader](https://logtalk.org/manuals/glossary.html#term-loader-file) files are used. In non-trivial applications, where source files are organized in multiple sub-directories, each sub-directory defining its own loader file, usually loaded by the main loader file. Wondering if you would be willing to add `loader.lgt` files to the repo to help run the Logtalk tools, including the linter, in a much easier to reproduce way. The loader files also typically load source files in an ideal order to minimize warnings and maximize use of static binding (Logtalk is **not** based on the predicate-prefixing mechanism implicit with (most) Prolog module systems).

**Comment by pmoura** [comment]
> I'm not sure about `user:runtime_entry/1` though. Since it defines an entry point, there should only ever be one `user:runtime_entry` definition from one file loaded at any time, so `multifile` seems incorrect.

Declaring this predicate as multifile is still required as we're defining a clause for a predicate in `user` inside a different module. Also, without the `multifile/1` directive, we still get an error compiling with Logtalk.
